### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by Innerdesert4346** [Zet0rz/nZombies-Unlimited#30]
If you want me to i can create a discord server for anyone who loves this mod like me or wants to post configs on something other than the steam workshop for people to maybe play it as a test or something and we can gather a community that wants to support you, i love the other nzombies gamemode you created and this one having a better system for "creative mode" will make map making a breeze and will make me and my friends happy so i can't wait. I'll make sure to give you the top role as well.

**Comment by Blueberryy** [comment]
There already a official Zet0r discord server https://discordapp.com/invite/zuujbaf

**Comment by Zet0rz** [comment]
The server Blueberryy linked to is my main server focused around me as a YouTuber and Twitch streamer (which I also am). It's a place focused on community, where we just have some fun chat and play some games together, as well as a place where you can get notified of when I or one of my friends stream. The server doesn't particularly focus on nZombies, though you can of course talk to me about it in there (and you can also DM me just by being in the server).

I have an nZombies-specific server too, however it is not open since I have no real outlet to reach members. I imagine I would open it after integrating it into Unlimited itself once it is playable.

**Comment by Innerdesert4346** [comment]
Well i have friends who play nzombies and have a way of telling people about it so if the official nzombies discord was open i could invite them to it, and i would rather have an nzombies focused discord for talking about nzombies.

**Comment by Zet0rz** [comment]
I guess I could try and get it ready earlier, I just imagine it would be like 5-10 people or and a relatively dead server until I can put a direct promotion to actual players in the gamemode. Do you think I should do that?

Also note btw, that it would probably only be to discuss with me Unlimited. It has channels and such for config creation, collaboration, sharing and all that, but with too few members you probably wouldn't really see much use out of these.

**Comment by sh4d0w59** [comment]
I know this is very late but an nzombies discord would be great even at this stage.  You could set it up so that it pushes github updates through one of the channels so people can stay up to date on what's going on in the gamemode.  Plus it would be a great place to directly discuss ideas and whatnot.

**Comment by Zet0rz** [comment]
I already have a server, but since it will be very empty until the gamemode is released, I chose to not open it yet at all. I suppose you could still join if you really wanted to, but it's gonna be a ghost town for another while. Tell me if you want the link anyway and I'll post it.

The plan was (is) to open it once the first playable version is ready on the Workshop. The gamemode's main menu would contain a button that links to the server.
